### ISSUE TITLE
TypeError: Cannot set property 'selection' of undefined

### ISSUE THREAD

**Issue by planger** [eclipsesource/graphical-lsp#112]
Currently, I receive the error below from time to time.

```
TypeError: Cannot set property 'selection' of undefined
    at e.handle (/home/philip/Git/OpenSource/graphical-lsp/client/packages/theia-glsp/src/sprotty/theia-selection-connector.ts:18:47)
    at e.handleAction (/home/philip/Git/OpenSource/graphical-lsp/client/node_modules/sprotty/src/base/actions/action-dispatcher.ts:75:40)
    at e.dispatch (/home/philip/Git/OpenSource/graphical-lsp/client/node_modules/sprotty/src/base/actions/action-dispatcher.ts:65:25)
    at e.handleEvent (/home/philip/Git/OpenSource/graphical-lsp/client/node_modules/sprotty/src/base/views/mouse-tool.ts:70:43)
    at e.mouseDown (/home/philip/Git/OpenSource/graphical-lsp/client/node_modules/sprotty/src/base/views/mouse-tool.ts:105:14)
    at e (/home/philip/Git/OpenSource/graphical-lsp/client/node_modules/snabbdom/src/modules/eventlisteners.ts:19:20)
    at r (/home/philip/Git/OpenSource/graphical-lsp/client/node_modules/snabbdom/src/modules/eventlisteners.ts:41:19)
    at SVGSVGElement.e (/home/philip/Git/OpenSource/graphical-lsp/client/node_modules/snabbdom/src/modules/eventlisteners.ts:47:5)

**Comment by planger** [comment]
We can avoid this error using the following code, which we should do anyway.
But I'm not sure why the selection service is undefined in the first place. So I leave this open for now without proposing a fix.

```typescript
@injectable()
export class SprottySelectionForwardingInitializer implements IActionHandlerInitializer {

    @inject(SelectionService) @optional() protected readonly selectionService: SelectionService;

    initialize(registry: ActionHandlerRegistry): void {
        if (this.selectionService === undefined) {
            return;
        }
        const selectionPropagatingHandler = new SprottySelectionForwardingActionHandler(this.selectionService);
        registry.register(SelectCommand.KIND, selectionPropagatingHandler);
    }
}
```

**Comment by tortmayr** [comment]
I'm not entirely sure why the selectionService is undefined from time to time. However in #113 I refactored the selectionService binding into the client specific DiagramConfiguration rather than doing it directly in the generic glue code.

At least for me this fixes the issue.
