### ISSUE TITLE
Execption when creating connections

### ISSUE THREAD

**Issue by tortmayr** [eclipsesource/graphical-lsp#54]
After multiple addtions/deletions of connections sometimes an exection occurs (see below)
Seems to be a server side issue where the indexer for new connections gets out of sync and then creates provides an already existing ID.

root ERROR 2:13:14 PM widget-0_sprotty e: Failed to execute command: Error: Duplicate ID in model: edge:weighted5
   at t.e.add (http://localhost:3000/bundle.js:1:64694)
   at t.add (http://localhost:3000/bundle.js:19:113204)
   at t.e.add (http://localhost:3000/bundle.js:1:64917)
   at t.add (http://localhost:3000/bundle.js:19:113204)
   at t.e.initializeRoot (http://localhost:3000/bundle.js:12:29766)
   at t.createRoot (http://localhost:3000/bundle.js:78:1498076)
   at t.execute (http://localhost:3000/bundle.js:12:402750)
   at http://localhost:3000/bundle.js:30:559357
   at new Promise (<anonymous>)
   at http://localhost:3000/bundle.js:30:559291
root ERROR 2:13:32 PM widget-0_sprotty e: Failed to execute command: Error: Duplicate ID in model: edge:weighted5
   at t.e.add (http://localhost:3000/bundle.js:1:64694)
   at t.add (http://localhost:3000/bundle.js:19:113204)
   at t.e.add (http://localhost:3000/bundle.js:1:64917)
   at t.add (http://localhost:3000/bundle.js:19:113204)
   at t.e.initializeRoot (http://localhost:3000/bundle.js:12:29766)
   at t.createRoot (http://localhost:3000/bundle.js:78:1498076)
   at t.execute (http://localhost:3000/bundle.js:12:402750)
   at http://localhost:3000/bundle.js:30:559357
   at new Promise (<anonymous>)
   at http://localhost:3000/bundle.js:30:559291

**Comment by tortmayr** [comment]
This is no longer reproducible and got probably fixed indirectly. Closing this for now.
